# Generated by Django 4.0.2 on 2022-03-11 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='url',
        ),
    ]
